[theme]
base = "light"
primaryColor = "#1D72B8"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#EEF6FC"
textColor = "#172033"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
